replicaCount: 1

image:
  hub: "docker.elastic.co/elasticsearch"
  name: "elasticsearch"
  tag: "7.14.0"
  pullPolicy: "IfNotPresent"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

securityContext:
  runAsUser: 1000
  privileged: false

service:
  type: ClusterIP
  port: 9200
  externalIPs: []
  extraPorts: []
  #  - name: ""
  #    port: ""

deployType: "StatefulSet"

volume:
  mountPath: "/usr/share/elasticsearch/data"

# When deployType is StatefulSet, enabled must be true
# This is used when deployType is StatefulSet
persistence:
  enabled: true
  volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "elasticsearch"
  resources:
    requests:
      storage: 10Gi

volumeClaimTemplate:
  storageClassName: ""
  resources:
    requests:
      storage: ""

# This is used when deployType is Deployment
volumeClaim:
  name: ""

extraVolumes: []

resources: {}

env: {}

readinessProbe:
  httpGet:
    path: /
    port: http
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}
