resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 4000m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80

affinity: { }