persistence:
  storageClass: "jenkins"
  size: "5Gi"

podLabels:
  version: "v2"

service:
  type: NodePort

resources:
  limits:
    memory: "6Gi"
    cpu: "400m"
  requests:
    memory: "1Gi"
    cpu: "100m"
