apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
    - "grafana.choshsh.com"
  gateways:
    - default/choshsh-gateway
  http:
    - name: "grafana"
      route:
        - destination:
            host: grafana
            subset: grafana-subset
            port:
              number: 80
      corsPolicy:
        allowOrigins:
          - regex: ".*\\.choshsh.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana
spec:
  host: grafana
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: grafana-subset
      labels:
        app: grafana
