apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
spec:
  destination:
    name: ""
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: manifest/istio-config
    repoURL: "https://github.com/SHsteak/devops-study.git"
    targetRevision: dev
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
