apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-network
spec:
  destination:
    name: ""
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: manifest/loki-stack/network
    repoURL: "https://github.com/choshsh/devops-study.git"
    targetRevision: dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
