apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: ""
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: argocd-deploy
    repoURL: "https://github.com/choshsh/devops-study.git"
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
