apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: ""
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: argocd-deploy
    repoURL: "https://github.com/SHsteak/devops-study.git"
    targetRevision: dev
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
