apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: choshsh-123
  region: ap-northeast-1

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: 1.10.2-eksbuild.1 # optional
    attachPolicyARNs: #optional
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    tags: # optional
      team: eks
