apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: choshsh-123
  region: ap-northeast-1
  tags:
    Owner: choshsh
    Stage: dev

vpc:
  subnets:
    public:
      ap-northeast-1a: {id: subnet-0548b8e401e6b16e3}
      ap-northeast-1d: {id: subnet-092d3004319638081}

managedNodeGroups:
  - name: ng-spot
    instanceTypes: ['t3a.small']
    labels:
      role: worker
    desiredCapacity: 3
    minSize: 3
    maxSize: 8
    volumeSize: 30
    volumeType: gp3
    spot: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
        labels: {aws-usage: 'cluster-ops'}
      wellKnownPolicies:
        autoScaler: true
      roleName: eksctl-cluster-autoscaler-role
      roleOnly: true
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    # - metadata:
    #     name: ebs-csi-controller-sa
    #     namespace: kube-system
    #   wellKnownPolicies:
    #     ebsCSIController: true
    #   # attachPolicyARNs:
    #   #   - 'arn:aws:iam::801167518143:policy/AWSLoadBalancerControllerIAMPolicy'

addons:
  - name: vpc-cni
    version: 1.10.2-eksbuild.1 # optional
    attachPolicyARNs: #optional
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: aws-ebs-csi-driver
    version: v1.6.1-eksbuild.1
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
