apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: choshsh-123
  region: ap-northeast-1
  tags:
    Owner: choshsh
    Stage: dev

vpc:
  subnets:
    public:
      ap-northeast-1a: {id: subnet-0548b8e401e6b16e3}
      ap-northeast-1d: {id: subnet-092d3004319638081}

managedNodeGroups:
  - name: ng-spot
    instanceTypes: ['t3a.small']
    labels: {role: workers}
    desiredCapacity: 2
    volumeSize: 20
    volumeType: gp3
    spot: true
