apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    name: ""
    namespace: jenkins
    server: "https://kubernetes.default.svc"
  source:
    path: manifest/jenkins
    repoURL: "https://github.com/SHsteak/devops-study.git"
    targetRevision: dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
