apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups
  labels:
    app: backups
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backups
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/backup
    server: master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: backups
