apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: http2
      port: 50000
      targetPort: http2
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        version: v2
    spec:
      hostAliases:
        - ip: "192.168.220.130"
          hostnames:
            - "localrepo"
      containers:
        - name: jenkins
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: jenkins/jenkins:2.307-jdk11
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "6Gi"
              cpu: "3000m"
            requests:
              memory: "1Gi"
              cpu: "300m"
          ports:
            - name: http
              containerPort: 8080
            - name: http2
              containerPort: 50000
          env:
            - name: TZ
              value: "Asia/Seoul"
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: jenkins-volume
              mountPath: /var/jenkins_home
  volumeClaimTemplates:
    - metadata:
        name: jenkins-volume
      spec:
        storageClassName: jenkins
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
