apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-caches
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-caches
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/jenkins-caches"
    type: DirectoryOrCreate
