apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
---
# jenkins 쿠버네티스 플러그인 사용을 위한 권한 설정
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: http-service
      port: 8080
      targetPort: http-service
    - name: http-agent
      port: 50000
      targetPort: http-agent
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        version: v1
    spec:
      serviceAccountName: jenkins
      # Private Image Repository dns 설정
      hostAliases:
        - ip: "192.168.220.130"
          hostnames:
            - "localrepo"
      containers:
        - name: jenkins
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: jenkins/jenkins:2.316-jdk11
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "4Gi"
          ports:
            - name: http-service
              containerPort: 8080 # 서비스
            - name: http-agent
              containerPort: 50000 # Master-Slave 노드 간 통신
          env:
            - name: TZ
              value: "Asia/Seoul"
          readinessProbe:
            httpGet:
              path: /login
              port: http-service
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: jenkins-volume
              mountPath: /var/jenkins_home
  volumeClaimTemplates:
    - metadata:
        name: jenkins-volume
      spec:
        storageClassName: nfs-client
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-workspace-pvc
  labels:
    app: jenkins-workspace
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
