apiVersion: v1
kind: Service
metadata:
  name: jenkins-test
spec:
  selector:
    app: jenkins-test
  ports:
    - name: http-service
      port: 8080
      targetPort: http-service
    - name: http-agent
      port: 50000
      targetPort: http-agent
  type: NodePort
  externalIPs:
    - 192.168.220.131
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.316-jdk11
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http-service
              containerPort: 8080 # 서비스
            - name: http-agent
              containerPort: 50000 # Master-Slave 노드 간 통신
          env:
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/casc_configs/jcasc.yaml"
            - name: TZ
              value: "Asia/Seoul"
          readinessProbe:
            httpGet:
              path: /login
              port: http-service
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: jenkins-volume
              mountPath: /var/jenkins_home
            - name: jenkins-cred
              mountPath: /run/secrets/choshsh-github-token
              subPath: choshsh-github-token
              readOnly: true
            - name: jenkins-cred
              mountPath: /run/secrets/slack-token
              subPath: slack-token
              readOnly: true
      initContainers:
        - name: init-plugins
          image: busybox
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          command:
            - sh
            - -c
            - |
              wget https://github.com/choshsh/jenkins-plugins/archive/refs/heads/master.zip -O /tmp/plugins.zip && \
                unzip /tmp/plugins.zip -d /tmp && \
                mkdir -p /tmp/jenkins_home/plugins && \
                mv /tmp/jenkins-plugins-master/*.hpi /tmp/jenkins_home/plugins/
          volumeMounts:
            - name: jenkins-volume
              mountPath: /tmp/jenkins_home
        - name: init-config
          image: busybox
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          command:
            - sh
            - -c
            - |
              mkdir -p /tmp/jenkins_home/casc_configs && \
                wget https://raw.githubusercontent.com/choshsh/devops-study/feature-jenkins-dsl/manifest/jenkins/jcasc.yaml -O /tmp/jenkins_home/casc_configs/jcasc.yaml
          volumeMounts:
            - name: jenkins-volume
              mountPath: /tmp/jenkins_home
      volumes:
        - name: jenkins-volume
          emptyDir: {}
        - name: jenkins-cred
          secret:
            secretName: jenkins-cred
