apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-workspace-pv
  labels:
    app: jenkins-workspace
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-workspace
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/jenkins-workspace
    server: master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-workspace-pvc
  namespace: jenkins
  labels:
    app: jenkins-workspace
spec:
  storageClassName: jenkins-workspace
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
