apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "common.names.fullname" . }}
spec:
  host: {{ template "common.names.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
    - name: v2
      labels:
        version: v2
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
