apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "was.fullname" . }}
spec:
  host: {{ include "was.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
    - name: "{{ include "was.fullname" . }}-subset"
      labels:
        app: {{ include "was.fullname" . }}
        version: {{ .Values.deploy.labels.version }}
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN