apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "was.fullname" . }}
spec:
  host: {{ include "was.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: "{{ include "was.fullname" . }}-subset"
      labels:
        version: {{ .Values.deploy.labels.version }}