apiVersion: v1
kind: Service
metadata:
  name: {{ include "was.fullname" . }}
  labels:
    {{- include "was.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.prometheus.enabled }}
    prometheus.io/path: "{{ .Values.actuator.path }}/prometheus"
    prometheus.io/port: {{ .Values.deploy.containerPort | quote }}
    prometheus.io/schema: "http"
    prometheus.io/scrape: "true"
  {{- end}}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.number }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.port.name }}
  selector:
    {{- include "was.selectorLabels" . | nindent 4 }}
