apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs: {{ .Values.service.externalIPs }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- range .Values.service.additionalPorts }}
    - port: {{ .port  }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
