{{- if eq .Values.deployType "StatefulSet" }}
{{- $fullname := (include "elasticsearch.fullname" .) -}}
{{- $labels := (include "elasticsearch.labels" .) -}}
{{- $selectorLabels := (include "elasticsearch.selectorLabels" .) -}}
{{- $serviceAccountName := (include "elasticsearch.serviceAccountName" .) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullname }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ $fullname }}-headless
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: www
        labels:
        {{- $labels | nindent 12 }}
      spec:
        {{- toYaml .Values.volumeClaimTemplate | nindent 8 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.hub }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote}}
          {{- end }}
          volumeMounts:
            - name: www
              mountPath: {{ .Values.volume.mountPath }}
          {{- range .Values.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .path }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}      
