apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      name: database
      targetPort: tcp
      appProtocol: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.26
          name: mysql
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "1"
            - name: MYSQL_ROOT_PASSWORD
              value: "P@ssw0rd!@#"
            - name: MYSQL_DATABASE
              value: "choshsh"
          args:
            - --lower_case_table_names=1
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              name: tcp
              protocol: TCP
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        storageClassName: nfs-client
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 2Gi
