apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  storageClassName: db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi