alertmanager:
  config:
    global: {}
    receivers:
      - name: slack-default
        slack_configs:
          - channel: "#devops"
            send_resolved: true
            title_link: "https://loki-prometheus-alertmanager.choshsh.com/#/alerts"
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Labels.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Labels.description }}
              *Details:*
                {{ range $key, $value := .Annotations -}}
                • *{{ $key }}:* {{ $value }}
                {{ end }}
              {{ end }}
    route:
      receiver: slack-default
      group_by: [alertname]
      group_wait: 30s # 처음 알림을 보내기 전 대기시간
      group_interval: 5m # 해당 그룹에 이미 알림이 있을 때 대기시간
      repeat_interval: 12h # 성공한 알림 다시 보냄
      routes: []

additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: Node
        rules:
          # Node 다운
          - alert: Node Down
            expr: up{job="kubernetes-nodes"} < 1
            for: 1m
            labels:
              severity: Critical
              summary: "Node Down"
              description: "1분 동안 노드 Down 상태"
            annotations:
              hostname: "{{ $labels.kubernetes_io_hostname }}"
              dashboard: "http://grafana.choshsh.com/d/4b545447f/kubernetes-all-in-one-cluster-monitoring-kr?orgId=1&var-node={{ $labels.kubernetes_io_hostname }}"
          # Node CPU 높음
          - alert: Node high CPU load
            expr: |
              (
                1 - avg by (instance,kubernetes_node) (
                  irate(node_cpu_seconds_total{mode="idle"}[5m])
                )
              ) > 0.8
            for: 5m
            labels:
              severity: Warning
              summary: "Node CPU high"
              description: "5분 동안 노드 CPU 사용량 80% 초과"
            annotations:
              hostname: "{{ $labels.kubernetes_node }}"
              instance: "{{ $labels.instance }}"
              dashboard: "http://grafana.choshsh.com/d/4b545447f/kubernetes-all-in-one-cluster-monitoring-kr?orgId=1&var-node={{ $labels.kubernetes_node }}"
          # Node Memory 높음
          - alert: Node high Memory usage
            expr: |
              (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)
                / node_memory_MemTotal_bytes > 0.9
            for: 5m
            labels:
              severity: Warning
              summary: "Node Memory high"
              description: "5분 동안 노드 Memory 사용량 90% 초과"
            annotations:
              hostname: "{{ $labels.kubernetes_node }}"
              instance: "{{ $labels.instance }}"
              dashboard: "http://grafana.choshsh.com/d/4b545447f/kubernetes-all-in-one-cluster-monitoring-kr?orgId=1&var-node={{ $labels.kubernetes_node }}"
          # Node Disk  높음
          - alert: Node high Disk usage
            expr: |
              sum by (kubernetes_node) (
                node_filesystem_size_bytes - node_filesystem_avail_bytes
              )
              /
              sum by (kubernetes_node) (
                node_filesystem_size_bytes
              ) > 0.8
            for: 5m
            labels:
              severity: Warning
              summary: "Node Disk high"
              description: "5분 동안 노드 Disk 사용량 80% 초과"
            annotations:
              hostname: "{{ $labels.kubernetes_node }}"
              instance: "{{ $labels.instance }}"
              dashboard: "http://grafana.choshsh.com/d/4b545447f/kubernetes-all-in-one-cluster-monitoring-kr?orgId=1&var-node={{ $labels.kubernetes_node }}"
      - name: Deploy
        rules:
          # Deployment 다운
          - alert: Deployment Down
            expr: |
              kube_deployment_status_replicas_available < 1 
                and time() - kube_deployment_created > 120
            for: 1m
            labels:
              severity: Critical
              summary: "Deployment Down"
              description: "1분 동안 available pod 0개"
            annotations:
              namespace: "{{ $labels.namespace }}"
              deployment: "{{ $labels.deployment }}"
              dashboard: "http://grafana.choshsh.com/d/XeS0yvN7z/kube-all-resource-log?orgId=1&refresh=10s&from=now-10m&to=now"
          # Statefulset 다운
          - alert: Statefulset Down
            expr: kube_statefulset_status_replicas_current < 1
            for: 1m
            labels:
              severity: Critical
              summary: "Statefulset Down"
              description: "1분 동안 available pod 0개"
            annotations:
              namespace: "{{ $labels.namespace }}"
              statefulset: "{{ $labels.statefulset }}"
              dashboard: "http://grafana.choshsh.com/d/XeS0yvN7z/kube-all-resource-log?orgId=1&refresh=10s&from=now-10m&to=now"
      - name: JVM
        rules:
          # JVM HEAP 메모리 높음
          - alert: Heap memory high
            expr: |
              sum by (kubernetes_name) (
                jvm_memory_used_bytes{area="heap"}
              )
              /
              sum by (kubernetes_name) (
                jvm_memory_max_bytes{area="heap"}
              ) > 0.8
            for: 1m
            labels:
              severity: Warning
              summary: "Heap memory high"
              description: "1분 동안 heap 메모리 사용률 80% 초과"
            annotations:
              service: "{{ $labels.kubernetes_name }}"
              dashboard: "http://grafana.choshsh.com/d/ku9BHmOnz/jvm-micrometer?orgId=1&var-application={{ $labels.kubernetes_name }}"
      - name: Istio
        rules:
          # http response 알림
          - alert: http response code - 5xx
            expr: rate(istio_requests_total{response_code=~"5.+"}[1m]) > 0
            for: 1m
            labels:
              severity: Critical
              summary: "http - server error"
              description: "http 서버 오류"
            annotations:
              app: "{{ $labels.app }}"
              response_code: "{{ $labels.response_code }}"
          - alert: http response code - 401, 403
            expr: rate(istio_requests_total{response_code=~"401|403"}[1m]) > 0
            for: 1m
            labels:
              severity: Warning
              summary: "http - unauthorized"
              description: "http 인증 오류"
            annotations:
              app: "{{ $labels.app }}"
              response_code: "{{ $labels.response_code }}"
