# Git url, 브랜치 등
{{- $global := .Values.global }}
{{- range $k, $v := .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $k }}
spec:
  destination:
    name: ""
    namespace: {{ $v.namespace | default "default" }}
    server: {{ $global.server }}
  source:
    path: {{ $v.source.path }}
    repoURL: {{ $global.repoURL }}
    targetRevision: {{ $global.targetRevision }}
    {{- if eq ($v.source.type | default "") "helm" }}
    helm: 
      {{ toYaml $v.source.helm | nindent 6 }}
    {{- else if eq ($v.source.type | default "") "dir" }}
    directory:
      recurse: {{ ($v.source.directory | default false) }}
    {{- end }}
  project: default
  {{- with $v.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---  
{{- end }}