apiVersion: v1
kind: Service
metadata:
  name: {{ include "was.fullname" . }}
  labels:
    {{- include "was.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.number }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.port.name }}
  selector:
    {{- include "was.selectorLabels" . | nindent 4 }}
