deploy:
  env:
    - name: TZ
      value: Asia/Seoul
    - name: JENKINS_REST_ENDPOINT
      value: http://jenkins.jenkins.svc.cluster.local:8080
  envFromConfigMap:
    configmapName: mysql
    items:
      url: MYSQL_URL
      jenkins-rest: MYSQL_DB
      user: MYSQL_USER
      jdbc-param: MYSQL_PARAM
  envFromSecret:
    name: jenkins-credß
    items:
      password: MYSQL_PASSWORD
      secretName: mysql-password
      jenkins-cred: JENKINS_REST_CREDENTIALS
fullnameOverride: jenkins-rest
image:
  name: jenkins-api-springboot
  pullPolicy: Always
  tag: "1636491014678"
nameOverride: jenkins-rest
podAnnotations:
  sidecar.istio.io/inject: "true"
