image:
  name: "choshsh-ui"
  pullPolicy: "Always"
  tag: "latest"

nameOverride: "choshsh-ui-loadtest"
fullnameOverride: "choshsh-ui-loadtest"

replicaCount: 2

deploy:
  env:
    - name: "TZ"
      value: "Asia/Seoul"
  args:
    - --spring.profiles.active=dev

podAnnotations:
  sidecar.istio.io/inject: "true"
