image:
  name: "choshsh-ui"
  pullPolicy: "Always"

nameOverride: "choshsh-ui"
fullnameOverride: "choshsh-ui"

deploy:
  env:
    - name: "TZ"
      value: "Asia/Seoul"
  envFromConfigMap:
    name: "mysql"
    items:
      - envName: MYSQL_URL
        key: "url"
      - envName: MYSQL_DB
        key: "choshsh-ui"
      - envName: MYSQL_USER
        key: "user"
      - envName: MYSQL_PARAM
        key: "jdbc-param"
  envFromSecret:
    envName: MYSQL_PASSWORD
    name: "mysql-password"
    key: "password"

podAnnotations:
  sidecar.istio.io/inject: "true"

prometheus:
  enabled: true
