deploy:
  env:
    - name: TZ
      value: Asia/Seoul
  envFromConfigMap:
    name: mysql
    items:
      url: MYSQL_URL
      choshsh-ui: MYSQL_DB
      user: MYSQL_USER
      jdbc-param: MYSQL_PARAM
  envFromSecret:
    name: MYSQL_PASSWORD
    items:
      password: mysql-password
fullnameOverride: choshsh-ui
image:
  name: choshsh-ui
  pullPolicy: Always
  tag: "1636561076156"
nameOverride: choshsh-ui
podAnnotations:
  sidecar.istio.io/inject: "true"
prometheus:
  enabled: true
