replicaCount: 1

image:
  hub: "choshsh"
  name: "choshsh-ui"
  tag: "latest"
  pullPolicy: "IfNotPresent"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploy:
  containerPort: 8080
  labels:
    version: "v2"
  args:
    - --spring.profiles.active=prod
  env: {}
  envFromConfigMap:
    {}
    # name: ""
    # items: {}
    #   key: env_name
  envFromSecret:
    {}
    # - secretName: ""
    #   envName: ""
    #   key: ""
  resources:
    {}
    # limits:
    #   cpu: 2000m
    #   memory: 2Gi
    # requests:
    #   cpu: 200m
    #   memory: 256Mi

service:
  type: ClusterIP
  port:
    number: 8080
    name: http
  labels: []
  externalIPs: []
  annotations: {}

actuator:
  path: "/actuator"

# prometheus JVM 모니터링 설정
prometheus:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

securityContext:
  runAsUser: 1000
  privileged: false

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
