grafana.ini:
  auth.anonymous:
    enabled: true
  security:
    allow_embedding: true

persistence:
  enabled: true
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-client

adminPassword: choshsh

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://loki-prometheus-server
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
