apiVersion: v1
kind: Pod
metadata:
  labels:
    run: zabbix-agent
  name: zabbix-agent
spec:
  containers:
    - env:
        # 이슈: 서비스 이름으로 설정하면 쿠버네티스 내부 dns 때문에 'cannot accept incoming connection for peer' 에러 발생
        # 조치: zabbix server pod의 ip로 하드코딩하면 해결
        - name: ZBX_SERVER_HOST
          value: "10.32.0.5"
      image: zabbix/zabbix-agent2
      name: zabbix-agent
      ports:
        - containerPort: 10050
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: zabbix-agent
  name: zabbix-agent
spec:
  ports:
    - port: 10050
      protocol: TCP
      targetPort: 10050
  selector:
    run: zabbix-agent
  type: ClusterIP
