apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zabbix
  name: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
  strategy: {}
  template:
    metadata:
      labels:
        app: zabbix
    spec:
      containers:
      - image: zabbix/zabbix-appliance
        name: zabbix-appliance
        ports:
        - containerPort: 80
          name: http
        - containerPort: 10051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zabbix
  name: zabbix
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 10051
    protocol: TCP
    targetPort: 10051
    name: active
  selector:
    app: zabbix
  type: ClusterIP
