repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive=true

      # args 문서: https://github.com/terraform-linters/tflint#usage
      - id: terraform_tflint
        exclude: environments/.*
        args:
          - >
            --args=--call-module-type=all
              --fix
              --minimum-failure-severity=warning
              --disable-rule=terraform_required_version
              --disable-rule=terraform_required_providers
              --disable-rule=terraform_module_version
              --no-color