apiVersion: apps/v1
kind: Deployment
metadata:
  name: empty-spot-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: &name empty-spot
      version: v1
  template:
    metadata:
      labels:
        app: *name
        version: v1
    spec:
      terminationGracePeriodSeconds: 1
      affinity:
        #        nodeAffinity:
        #          requiredDuringSchedulingIgnoredDuringExecution:
        #            nodeSelectorTerms:
        #              - matchExpressions:
        ##                  - key: beta.kubernetes.io/instance-type
        ##                    operator: In
        ##                    values:
        ##                      - "m7i-flex.large"
        #                  - key: karpenter.sh/capacity-type
        #                    operator: In
        #                    values:
        #                      - "spot"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - *name
                  - key: version
                    operator: In
                    values:
                      - v1
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "capacity-spread"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - *name
              - key: version
                operator: In
                values:
                  - v1
      containers:
        - name: default
          image: alpine:latest
          command: [ "sleep", "infinity" ]

