apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator-1-20-0
  namespace: istio-system
spec:
  revision: 1-20-0
  components:
    base:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
  hub: docker.io/istio
  meshConfig:
    defaultConfig:
      proxyMetadata: { }
    enablePrometheusMerge: true
  profile: default
  tag: 1.20.0
  values:
    defaultRevision: ""
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        env:
          TERMINATION_DRAIN_DURATION_SECONDS: 60
        name: istio-ingressgateway
        type: LoadBalancer