apiVersion: v1
kind: Namespace
metadata:
  name: itsm
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - port: 3306
      name: http
      targetPort: http
      appProtocol: mysql
  type: ClusterIP
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
      version: v2
  template:
    metadata:
      labels:
        app: db
        version: v2
    spec:
      containers:
        - image: mysql:8.0.26
          name: db
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "1"
            - name: MYSQL_ROOT_PASSWORD
              value: "P@ssw0rd!@#"
            - name: MYSQL_DATABASE
              value: "itsmv"
          args:
            - --lower_case_table_names=1
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              name: http
              protocol: TCP
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        storageClassName: db
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
