global:
  targetRevision: dev

applications:
  nfs-subdir-external-provisioner:
    namespace: default
    type: helmRepo
    source:
      chart: nfs-subdir-external-provisioner
      helm:
        values: |-
          nfs:
            server: master
            path: /data
          podAnnotations:
            sidecar.istio.io/inject: "false"
          storageClass:
            name: dynamic
      repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      targetRevision: 4.0.15
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  jenkins:
    namespace: jenkins
    type: dir
    source:
      path: manifest/jenkins
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # itsm-db
  choshsh-db:
    namespace: default
    type: dir
    source:
      path: manifest/mysql
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  choshsh-ui:
    namespace: default
    type: helm
    source:
      path: manifest/was
      helm:
        valueFiles:
          - values-choshsh-ui.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
