# Default values for argocd-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  repoURL: "https://github.com/choshsh/devops-study.git"
  targetRevision: HEAD
  server: "https://kubernetes.default.svc"

# 배포를 위한 ArgoCD 애플리케이션
#
# namespace       배포할 네임스페이스
# source.path     Git Repo에서 상대경로
# source.type     배포할 manifest의 타입 (dir or helm)
#   1. dir        기본 (kubectl apply -f)
#      directory  하위 폴더 배포 여부 (true or false)
#   2. helm       helm 차트 (helm isntall <path> -f <value파일>)
# syncPolicy      (선택) 자동 sync 여부 - 이 옵션을 활성화하면 롤백 기능 사용 불가
# syncPolicy.automated.prune    리소스 업데이트 시 삭제하고 생성 여부
# syncPolicy.automated.selfHeal 리소스 차이가 생길 경우 5초마다 sync 시도
applications:
  # istio-config
  istio-default:
    namespace: default
    source:
      path: manifest/istio-default
      type: dir
      directory: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # jenkins
  jenkins:
    namespace: jenkins
    source:
      path: manifest/jenkins
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # # nfs-subdir-external-provisioner
  # nfs-subdir-external-provisioner
  #   namespace: default
  #   source:
  #     path: manifest/nfs-subdir-external-provisioner
  #     type: helm
  #     helm:
  #       valueFiles:
  #         - values-choshsh.yaml
  #   syncPolicy:
  #     automated:
  #       prune: true
  #       selfHeal: true
  # itsm-db
  choshsh-db:
    namespace: default
    source:
      path: manifest/mysql
      type: dir
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # choshsh-ui-network
  choshsh-ui-vs:
    namespace: default
    source:
      path: manifest/was/network
      type: dir
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # choshsh-ui
  choshsh-ui:
    namespace: default
    source:
      path: manifest/was
      type: helm
      helm:
        valueFiles:
          - values-choshsh-ui.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # choshsh-ui-loadtest
  choshsh-ui-loadtest:
    namespace: default
    source:
      path: manifest/was
      type: helm
      helm:
        valueFiles:
          - values-choshsh-ui-loadtest.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # jenkins-rest
  jenkins-rest:
    namespace: default
    source:
      path: manifest/was
      type: helm
      helm:
        valueFiles:
          - values-jenkins-api-springboot.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # loki-network
  loki-network:
    namespace: monitoring
    source:
      path: manifest/loki-stack/network
      type: dir
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # Grafana
  grafana:
    namespace: monitoring
    source:
      path: manifest/grafana
      type: helm
      helm:
        valueFiles:
          - values-choshsh.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # Grafana
  node-exporter:
    namespace: monitoring
    source:
      path: manifest/prometheus-node-exporter
      type: helm
      helm:
        valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
