global:
  targetRevision: HEAD
applications:
  # istio-config
  istio-default:
    namespace: default
    type: dir
    source:
      path: manifest/istio-default
      recurse: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # jenkins
  jenkins:
    namespace: jenkins
    type: dir
    source:
      path: manifest/jenkins
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # itsm-db
  choshsh-db:
    namespace: default
    type: dir
    source:
      path: manifest/mysql
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # choshsh-ui-network
  choshsh-ui-vs:
    namespace: default
    type: dir
    source:
      path: manifest/was/network
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # choshsh-ui
  choshsh-ui:
    namespace: default
    type: helm
    source:
      path: manifest/was
      helm:
        valueFiles:
          - values-choshsh-ui.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # choshsh-ui-loadtest
  choshsh-ui-loadtest:
    namespace: default
    type: helm
    source:
      path: manifest/was
      helm:
        valueFiles:
          - values-choshsh-ui-loadtest.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # jenkins-rest
  jenkins-rest:
    namespace: default
    type: helm
    source:
      path: manifest/was
      helm:
        valueFiles:
          - values-jenkins-api-springboot.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
