global:
  targetRevision: dev

applications:
  nfs-subdir-external-provisioner:
    namespace: default
    source:
      path: manifest/nfs-subdir-external-provisioner
      type: helm
      helm:
        valueFiles:
          - values-choshsh.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  jenkins:
    namespace: jenkins
    source:
      path: manifest/jenkins
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # itsm-db
  choshsh-db:
    namespace: default
    source:
      path: manifest/mysql
      type: dir
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  choshsh-ui:
    namespace: default
    source:
      path: manifest/was
      type: helm
      helm:
        valueFiles:
          - values-choshsh-ui.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
