# Default values for argocd-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  repoURL: "https://github.com/choshsh/devops-study.git"
  targetRevision: HEAD
  server: "https://kubernetes.default.svc"

# 배포를 위한 ArgoCD 애플리케이션
#
# namespace       배포할 네임스페이스
# type     배포할 manifest의 타입 (dir / helm / helmRepo)
#   1. dir        기본 (kubectl apply -f)
#      directory  하위 폴더 배포 여부 (true or false)
#   2. helm       현재 repository에 있는 helm 차트 (helm isntall <path> -f <value파일>)
#   3. helmRepo   원격 repository에 있는 helm 차트
# source.path     Git Repo에서 상대경로
# syncPolicy      (선택) 자동 sync 여부 - 이 옵션을 활성화하면 롤백 기능 사용 불가
# syncPolicy.automated.prune    리소스 업데이트 시 삭제하고 생성 여부
# syncPolicy.automated.selfHeal 리소스 차이가 생길 경우 5초마다 sync 시도
applications: {}
