# Default values for argocd-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  repoURL: "https://github.com/choshsh/devops-study.git"
  # branch switch - prod/dev
  targetRevision: HEAD
  server: "https://kubernetes.default.svc"

argocd:
  # istio-config
  - name: istio-config
    namespace: default
    source:
      path: manifest/istio-config
      type: dir
      directory: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # jenkins
  - name: jenkins
    namespace: jenkins
    source:
      path: manifest/jenkins
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # nfs-subdir-external-provisioner
  - name: nfs-subdir-external-provisioner
    namespace: default
    source:
      path: manifest/nfs-subdir-external-provisioner
      type: helm
      helm:
        valueFiles:
          - values-choshsh.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # itsm-db
  - name: itsm-db
    namespace: dev
    source:
      path: manifest/itsm
      type: dir
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
  # itsm-was
  - name: itsm-was
    namespace: dev
    source:
      path: manifest/itsm
      type: helm
      helm:
        valueFiles:
          - dev-values.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  # loki-network
  - name: loki-network
    namespace: default
    source:
      path: manifest/loki-stack/network
      type: dir
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
