apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itsm-was
spec:
  destination:
    name: ""
    namespace: dev
    server: "https://kubernetes.default.svc"
  source:
    path: manifest/was
    repoURL: "https://github.com/choshsh/devops-study.git"
    targetRevision: dev
    helm:
      valueFiles:
        - dev-values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
