apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger
  namespace: istio-system
spec:
  hosts:
    - "jaeger.choshsh.com"
  gateways:
    - default/choshsh-gateway
  http:
    - name: "jaeger-http"
      match:
        - port: 80
      route:
        - destination:
            host: tracing
            subset: jaeger-subset
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: jaeger
  namespace: istio-system
spec:
  host: tracing
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
    - name: jaeger-subset
      labels:
        app: jaeger
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
